#!/bin/bash
echo " =========================================================================================="



echo "            Name & description: initdev ; proceed with a project organization and apply a set of pre-  configuration; a project initialization tool  "


echo " =========================================================================================="


echo "           Syntax: Project_name Project_type License_type git"



echo " =========================================================================================="



echo "          Args: it has 4 arguments: Project name, project type (c,py,cpp,latex,BEAMER) , license type (GPL, MIT) and initialization of a deposit git "

echo " =========================================================================================="



echo "         Author: BELMOKHTAR Maria ; mariarah@outlook..fr"



echo " ==========================================================================================" 
